name: CI

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Build page
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "Github Actions"
          
          yarn
          yarn run test
          yarn run build
      - name: "Setup SSH key"
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.WEBSERVER_SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.WEBSERVER_SSH_KNOWN_HOSTS}}
      - name: "Deploy to Hetzner"
        run: |
          rsync -avz --no-p --no-times ./public/ $SSH_CONNECTION:/srv/webserver/www/verein-website/
        env:
          SSH_CONNECTION: ${{secrets.WEBSERVER_SSH_CONNECTION}}
#      - name: "Deploy to github pages"
#        uses: JamesIves/github-pages-deploy-action@4.1.4
#        with:
#          branch: gh-pages
#          folder: public
