name: CI

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Build page
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "Github Actions"
          
          yarn
          yarn run test
          yarn run build
      - name: "Setup SSH key"
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.WEBSITE_SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.WEBSITE_SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ${{github.workspace}}/../private.key
      - name: "Deploy to Hetzner"
        run: |
          rsync -avz --no-p -e "ssh -i $SSH_KEY_PATH" ./public/ github_deployment@188.245.229.184:/srv/webserver/www/verein-website/
#      - name: "Deploy to github pages"
#        uses: JamesIves/github-pages-deploy-action@4.1.4
#        with:
#          branch: gh-pages
#          folder: public
